name: Issue Close Require

on:

jobs:
  close-issues:
    if: github.repository == 'vitejs/vite'
    runs-on: ubuntu-22.04
    steps:
      - name: needs reproduction
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: "needs reproduction"
          inactive-day: 3
